####################################################################################################

version: 1

####################################################################################################

formatters:

  simple:
    format: '%(asctime)s - %(name)s - %(module)s.%(funcName)s - %(levelname)s - %(message)s'

  ansi:
#   RESET_SEQ = "\033[0m"
#   COLOR_SEQ = "\033[1;%dm"
#   BOLD_SEQ = "\033[1m"
    format: '<ESC>[1;32m%(asctime)s<ESC>[0m - <ESC>[1;34m%(name)s - %(module)s.%(funcName)s<ESC>[0m - <ESC>[1;31m%(levelname)s<ESC>[0m - %(message)s'

####################################################################################################

handlers:

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: ansi
    stream: ext://sys.stdout

  console-stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: ansi
    stream: ext://sys.stderr

  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: logconfig.log
    maxBytes: 1024
    backupCount: 3

####################################################################################################

root:
  level: DEBUG
  #level: INFO
  #level: WARNING
  #handlers: [console]

####################################################################################################

loggers:

##################################################
#
# Programs
#

  radio-crawler:
    level: DEBUG
    #level: INFO
    handlers: [console]
    propagate: no

##################################################
#
# Modules
#

  RadioCrawler:
    level: DEBUG
    #level: INFO
    #level: WARNING
    handlers: [console-stderr]
